/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gamelabirinto2;

import java.awt.event.KeyEvent;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 *
 * @author Tony L
 */
public class Labirinto2 extends javax.swing.JFrame {
    
    Mapa m = new Mapa();

    
    int xx=0, yy=0;
    
    public Labirinto2() {
        initComponents();
                
        m.Logica(8, 7);

        Computador comp;
        comp = new Computador("Teste");
        comp.start();
        
        jTextArea1.setText(m.MontaMapa(xx, yy));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP){  
            if(yy-1>=0 && yy-1<=m.c){
                if(m.Matriz[yy-1][xx] == 1){
                    yy = yy-1;
                
                jTextArea1.setText(m.MontaMapa(xx, yy));
            }   
        }
        } else if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            if(xx-1>=0 && xx-1<=m.l){
                if(m.Matriz[yy][xx-1] == 1){
                    xx = xx-1;   
                    jTextArea1.setText(m.MontaMapa(xx, yy));
            }   
        }
        } else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            System.out.println("De   x:["+xx+"]y:["+yy+"]\nPara x:["+(xx+1)+"]y:["+yy+"] | linhas: "+m.l+" | Colunas: "+m.c+"");
            if(xx+1>=0 && xx+1<m.c){
                if(m.Matriz[yy][xx+1] == 1){
                 xx = xx+1; 
                jTextArea1.setText(m.MontaMapa(xx, yy));
            }   
        }
        } else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            System.out.println("De   x:["+xx+"]y:["+yy+"]\nPara x:["+xx+"]y:["+(yy+1)+"] | linhas: "+m.l+" | Colunas: "+m.c+"");
            if(yy+1>=0 && yy+1<m.l){
                if(m.Matriz[yy+1][xx] == 1){
                    yy = yy+1;
                    jTextArea1.setText(m.MontaMapa(xx, yy));
            }   
        }
        } 
        //JOptionPane.showInputDialog(evt.getKeyCode());
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Labirinto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Labirinto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Labirinto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Labirinto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Labirinto2().setVisible(true);
            }
        });
    
    
    
    
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
